version: "3.6"

services:
    database:
        image: mysql:8.0.29
        container_name: database
        restart: always
        ports:
            - 3306:3306
        volumes:
            - ./mysql/dados:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=1223456
            - MYSQL_ROOT_HOST=%
        networks:
            - vendas-net

    server:
        container_name: server
        build:
            context: ./server
            dockerfile: Dockerfile
        ports:
            - 8081:8081
        depends_on:
            - database
        environment:
            - EUREKA.CLIENT.SERVICEURL.DEFAULTZONE=http://localhost:8081/eureka/
        networks:
            - vendas-net

    gateway:
        container_name: gateway
        build:
            context: ./gateway
            dockerfile: Dockerfile
        ports:
            - 8082:8082
        depends_on:
            - server
        environment:
            - EUREKA.CLIENT.SERVICEURL.DEFAULTZONE=http://server:8081/eureca/
        networks:
            - vendas-net

    app-pedidos:
        container_name: app-pedidos
        build:
            context: ./pedidos
            dockerfile: Dockerfile
        ports:
            - 8080:8080
        depends_on:
            - server
            - database
            - rabbitmq
        environment:
            - SPRING_DATASOURCE_URL=jdbc:mysql://database:3306/db-pedidos?createDatabaseIfNotExist=true
            - SPRING_DATASOURCE_USERNAME=root
            - SPRING_DATASOURCE_PASSWORD=1223456
            - EUREKA.CLIENT.SERVICEURL.DEFAULTZONE=http://server:8081/eureca/
        networks:
            - vendas-net

    rabbitmq:
        image: rabbitmq:3.10-management
        container_name: rabbitmq
        restart: always
        ports:
            - 5672:5672
            - 15672:15672
        volumes:
            - ./rabbit/dados:/var/lib/rabbitmq/
        depends_on:
          - server
        environment:
            - RABBITMQ_DEFAULT_USER=admin
            - RABBITMQ_DEFAULT_PASS=1223456
        networks:
            - vendas-net

networks:
    vendas-net:
        driver: bridge
